name: Build and Publish Multi-Arch Docker Image

on:
  push:
    branches:
      - '**'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      packages: read
    steps:
      - name: Checkout this repo
        uses: actions/checkout@v4

      - name: Read version from file
        id: version
        run: |
          VERSION=$(cat hyperswitch-web/gitVersion)
          echo "VERSION=$VERSION" >> $GITHUB_OUTPUT

      - name: Check if GHCR image exists
        id: check_tag
        shell: bash
        run: |
          VERSION="v${{ steps.version.outputs.VERSION }}-helm"
          IMAGE_NAME="centerionware/hyperswitch-web-autobuild/hyperswitch-web"
          URL="https://ghcr.io/v2/${IMAGE_NAME}/manifests/${VERSION}"

          echo "Checking GHCR for: $IMAGE_NAME:$VERSION"

          STATUS=$(curl -s -o /dev/null -w "%{http_code}" \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.docker.distribution.manifest.v2+json" \
            "$URL")

          if [[ "$STATUS" == "200" ]]; then
            echo "Image exists."
            echo "skip_build=true" >> $GITHUB_ENV
          else
            echo "Image not found. Status code: $STATUS"
            echo "skip_build=false" >> $GITHUB_ENV
          fi

      - name: Clone hyperswitch-web repo at version branch
        if: env.skip_build == 'false'
        run: |
          git clone --branch "v${{ steps.version.outputs.VERSION }}" https://github.com/juspay/hyperswitch-web.git other-repo

      - name: Set up Docker Buildx
        if: env.skip_build == 'false'
        uses: docker/setup-buildx-action@v3

      - name: Log in to registry
        if: env.skip_build == 'false'
        # This is where you will update the PAT to GITHUB_TOKEN
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build and push multi-arch Docker image
        if: env.skip_build == 'false'
        run: |
          IMAGE_TAG=ghcr.io/centerionware/hyperswitch-web-autobuild/hyperswitch-web:v${{ steps.version.outputs.VERSION }}-helm

          docker buildx build \
            --platform linux/amd64,linux/arm64 \
            --file other-repo/Dockerfile.helm \
            --push \
            --tag $IMAGE_TAG \
            other-repo
