name: Build and Publish Multi-Arch Docker Image

on:
  push:
    branches:
      - '**'

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout this repo
        uses: actions/checkout@v4

      - name: Read version from file
        id: version
        run: |
          VERSION=$(cat hyperswitch-web/gitVersion)
          echo "VERSION=$VERSION" >> $GITHUB_OUTPUT

      - name: Clone hyperswitch-web repo at version branch
        run: |
          git clone --branch "v${{ steps.version.outputs.VERSION }}" https://github.com/juspay/hyperswitch-web.git other-repo

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry (GHCR)
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Build and push multi-arch Docker image
        run: |
          IMAGE_TAG=ghcr.io/centerionware/hyperswitch-web-autobuild/hyperswitch-web:v${{ steps.version.outputs.VERSION }}-helm

          docker buildx build \
            --platform linux/amd64,linux/arm64 \
            --file other-repo/Dockerfile.helm \
            --push \
            --tag $IMAGE_TAG \
            other-repo
          echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_OUTPUT
      - name: Push Docker image to GHCR
        run: |
          docker push "${{ steps.build.outputs.IMAGE_TAG }}"